# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=false

# Mod properties
mod_version = 3.7.0
archives_name = conveyor_belt_plus

# Minecraft properties
minecraft_version = 1.20.1

# Dependencies
forge_version = 47.4.10
jei_version = 15.20.0.106
jade_version = 11.13.3+forge
rts_version = 1.1.8-beta
